import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-jakarta)", "sans-serif"],
        jakarta: ["var(--font-jakarta)", "sans-serif"],
        "hero-h1-mobile": ["var(--font-jakarta)", "sans-serif"],
        "step-number": ["var(--font-jakarta)", "sans-serif"],
        body: ["var(--font-jakarta)", "sans-serif"],
        "section-h2-mobile": ["var(--font-jakarta)", "sans-serif"],
        "section-h2": ["var(--font-jakarta)", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "hero-subheadline": ["var(--font-jakarta)", "sans-serif"],
        "hero-h1": ["var(--font-jakarta)", "sans-serif"],
      },
      fontSize: {
        "hero-h1-mobile": [
          "56px",
          { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "900" },
        ],
        "step-number": ["120px", { lineHeight: "1.0", fontWeight: "900" }],
        body: ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "section-h2-mobile": ["40px", { lineHeight: "1.1", fontWeight: "900" }],
        "section-h2": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "900" },
        ],
        "label-mono": [
          "14px",
          { lineHeight: "1.0", letterSpacing: "0.2em", fontWeight: "700" },
        ],
        "hero-subheadline": ["24px", { lineHeight: "1.6", fontWeight: "400" }],
        "hero-h1": [
          "96px",
          { lineHeight: "1.0", letterSpacing: "-0.05em", fontWeight: "900" },
        ],
      },
      spacing: {
        "container-max-width": "1280px",
        "bento-gap": "24px",
        "hero-top-padding": "160px",
        gutter: "24px",
        "section-v-padding": "128px",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        "surface-darker": "hsl(var(--surface-darker))",
        ink: "#111111",
        paper: "#f5f5f5",
        "background-dark": "#0a0a0a",
        "background-light": "#f8f5f5",
        "surface-dark": "#121212",
        "surface-border": "#392828",
        "text-main": "#FFFFFF",
        "text-muted": "#a3a3a3",
        "primary-hover": "#0284c7",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "on-tertiary-fixed": "#2c1600",
        "on-background": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "on-primary-container": "#003751",
        "tertiary-container": "#de8712",
        "on-tertiary-fixed-variant": "#693c00",
        "primary-container": "#0ea5e9",
        "on-secondary-fixed": "#001d31",
        "error-container": "#93000a",
        "surface-alt-1": "#050505",
        "primary-fixed-dim": "#89ceff",
        "on-secondary": "#003351",
        "cyan-glow": "rgba(14, 165, 233, 0.25)",
        "on-primary-fixed-variant": "#004c6e",
        "on-tertiary": "#492900",
        "on-secondary-fixed-variant": "#004b73",
        "on-error": "#690005",
        "surface-container-high": "#2a2a2a",
        "text-primary": "#f5f5f5",
        "secondary-fixed-dim": "#93ccff",
        "surface-variant": "#353534",
        "on-primary": "#00344d",
        "primary-fixed": "#c9e6ff",
        "surface-container-highest": "#353534",
        "surface-alt-2": "#080808",
        "secondary-container": "#3198dc",
        error: "#ffb4ab",
        outline: "#88929b",
        "on-tertiary-container": "#4d2b00",
        "on-surface-variant": "#bec8d2",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#3a3939",
        "inverse-on-surface": "#313030",
        "surface-tint": "#89ceff",
        "secondary-fixed": "#cce5ff",
        "on-surface": "#e5e2e1",
        "card-surface": "#121212",
        surface: "#131313",
        "border-subtle": "#272727",
        "outline-variant": "#3e4850",
        "text-secondary": "#9ca3af",
        "surface-dim": "#131313",
        "tertiary-fixed-dim": "#ffb86e",
        "on-secondary-container": "#002c47",
        "surface-container-lowest": "#0e0e0e",
        tertiary: "#ffb86e",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#006591",
        "on-primary-fixed": "#001e2f",
        "tertiary-fixed": "#ffdcbd",
        danger: "#ef0b0b",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        neo: "4px 4px 0px 0px rgba(0,0,0,1)",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "fake-progress": {
          "0%": { width: "0%" },
          "40%": { width: "55%" },
          "70%": { width: "72%" },
          "90%": { width: "80%" },
          "100%": { width: "80%" },
        },
        "slow-ping": {
          "0%": { transform: "scale(1)", opacity: "0.6" },
          "70%": { transform: "scale(1.8)", opacity: "0" },
          "100%": { transform: "scale(1.8)", opacity: "0" },
        },
        "svg-trace": {
          "0%": { strokeDashoffset: "600", opacity: "1" },
          "70%": { strokeDashoffset: "0", opacity: "1" },
          "85%": { strokeDashoffset: "0", opacity: "0" },
          "100%": { strokeDashoffset: "600", opacity: "0" },
        },
        "fade-cycle": {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "15%": { opacity: "1", transform: "translateY(0)" },
          "80%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(-4px)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        zoomIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        shimmer: "shimmer 1.8s linear infinite",
        "fake-progress":
          "fake-progress 2.5s cubic-bezier(0.4, 0, 0.2, 1) forwards",
        "slow-ping": "slow-ping 2s ease-out infinite",
        "svg-trace": "svg-trace 3s ease-in-out infinite",
        "fade-cycle": "fade-cycle 2.5s ease-in-out both",
        fadeIn: "fadeIn 0.2s ease-out",
        zoomIn: "zoomIn 0.3s ease-out forwards",
      },
    },
  },
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  plugins: [require("tailwindcss-animate")],
};
export default config;
